/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */


  "docs": [       
    {
      "type": "category",
      "label": "Risk Platform",
      "items": [
          "Risk-Platform/EPRG-Provider-Portal",
          "Risk-Platform/Zephyr-Point-of-Care-Portal",
          "Risk-Platform/DataRAP",
          "Risk-Platform/TCoE"
      ]
    },
    {
      "type": "category",
      "label": "Clinical-Care-Enablement",
      "items": [
        "Clinical-Care-Enablement/Care-Delivery-Support-System",
        "Clinical-Care-Enablement/WellMed-Directory",
        "Clinical-Care-Enablement/Enterprise-Clinic-Bonus-Tool",
        "Clinical-Care-Enablement/Sensitive-Code-Suppression-Depository",
        "Clinical-Care-Enablement/One-Source-Cares-ACI",
        "Clinical-Care-Enablement/PTG-Cost-and-Care-App",
        "Clinical-Care-Enablement/Jotform",
        "Clinical-Care-Enablement/TripSpark",
        "Clinical-Care-Enablement/eClinical-Works",
        "Clinical-Care-Enablement/Payer-Grid-Expansion",
        "Clinical-Care-Enablement/Bexar-Imaging",
        "Clinical-Care-Enablement/Home-Care-Dimension"
      ]
    },

    {
      "type": "category",
      "label": "Delegated Platform",
      "items": [
          "Delegated-Platform/IKA-Claims",
          "Delegated-Platform/Case-Management-Salesforce",
          "Delegated-Platform/Utilization-Management-Trucare-Tech-Audit",

      ]
    },

    {
      "type": "category",
      "label": "Infrastructure Operations",
      "items": [
          "Infrastructure-Operations/Infra-Ops",
          
      ]
    },

    {
      "type": "category",
      "label": "Admin/Arch./Info./sec./Audit",
      "items": [
          "Admin-Arch-Info -sec-Audit-ITSM/Service-Now",
          "Admin-Arch-Info -sec-Audit-ITSM/Access-Management-Ops",
          "Admin-Arch-Info -sec-Audit-ITSM/Audit-Risk-Management",
          "Admin-Arch-Info -sec-Audit-ITSM/Information-Security",
          "Admin-Arch-Info -sec-Audit-ITSM/Finance-Ops",
          "Admin-Arch-Info -sec-Audit-ITSM/Cloud-CCoE",
          "Admin-Arch-Info -sec-Audit-ITSM/Infra-Ops-Desktop",
          "Admin-Arch-Info -sec-Audit-ITSM/SQL-Reporting-Migration"
          
      ]
    },

    {
      "type": "category",
      "label": "Data Services",
      "items": [
          "Data-Services/Integration-Services-Development",
          "Data-Services/Cloud-Operations"
          
      ]
    },

  ]
};

module.exports = sidebars;
